<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $writingServiceRequest->request_id], ['confirm' => __('Are you sure you want to delete # {0}?', $writingServiceRequest->request_id), 'class' => 'side-nav-item']) ?>
            <?= $this->Html->link(__('List Writing Service Requests'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column column-80">
        <div class="writingServiceRequests form content">
            <?= $this->Form->create($writingServiceRequest, ['type' => 'file']) ?>
            <fieldset>
                <legend><?= __('Edit Writing Service Request') ?></legend>
                <?= $this->Form->hidden('user_id', ['value' => $userId]) ?>
                <?= $this->Form->select(
                    'service_type',
                    [
                        '' => 'Please select a service',
                        'creative_writing' => 'Creative Writing',
                        'editing' => 'Editing',
                        'proofreading' => 'Proofreading',
                    ],
                    ['class' => 'form-select']
                ) ?>
                <?= $this->Form->select(
                    'word_count_range',
                    [
                        '' => 'Please select a word count range',
                        'under_5000' => 'Under 5000',
                        '5000_20000' => '5000 - 20000',
                        '20000_50000' => '20000 - 50000',
                        '50000_plus' => '50000+',
                    ],
                    ['class' => 'form-select']
                ) ?>
                <?= $this->Form->control('notes') ?>
                <?= $this->Form->control('final_price') ?>
                <?= $this->Form->control('request_status') ?>

                <!-- Display the valuation automatically generated by the system -->
                <div class="mb-3">
                    <label class="form-label fw-bold"><?= __('Estimated Price') ?></label>
                    <input type="text" class="form-control" value="$<?= h(number_format($writingServiceRequest->estimated_price, 2)) ?>" readonly>
                </div>

                <!-- Display creation/modify time -->
                <div class="mb-3">
                    <label class="form-label fw-bold"><?= __('Created At') ?></label>
                    <p class="form-control-plaintext"><?= h($writingServiceRequest->created_at) ?></p>
                </div>
                <div class="mb-3">
                    <label class="form-label fw-bold"><?= __('Updated At') ?></label>
                    <p class="form-control-plaintext"><?= h($writingServiceRequest->updated_at) ?></p>
                </div>

                <!-- Document upload -->
                <div class="mb-3">
                    <label class="form-label fw-bold"><?= __('Existing Document') ?></label>
                    <?php if (!empty($writingServiceRequest->document)): ?>
                        <?= $this->Html->link('View Document', '/' . $writingServiceRequest->document, ['target' => '_blank']) ?>
                    <?php else: ?>
                        <span><?= __('No Document Uploaded') ?></span>
                    <?php endif; ?>
                </div>
                <div class="mb-3">
                    <?= $this->Form->label('document', __('Upload New Document (TXT, PDF, Word)'), ['class' => 'form-label fw-bold']) ?>
                    <?= $this->Form->file('document', ['class' => 'form-control']) ?>
                </div>
            </fieldset>
            <?= $this->Form->button(__('Submit')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>
