name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-24.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cakephp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.1'
            db-type: 'mysql'
            dependencies: 'lowest'
          - php-version: '8.2'
            db-type: 'mysql'
            dependencies: 'highest'
          - php-version: '8.3'
            db-type: 'mysql'
            dependencies: 'highest'
          - php-version: '8.4'
            db-type: 'mysql'
            dependencies: 'highest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql
          ini-values: zend.assertions=1
          coverage: none

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run PHPUnit
        env:
          DATABASE_TEST_URL: mysql://root:root@127.0.0.1/cakephp
          SECURITY_SALT: ${{ secrets.SECURITY_SALT }}
          EMAIL_TRANSPORT_CLASS: Debug
        run: vendor/bin/phpunit

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
          coverage: none
          tools: cs2pr, phpstan:1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        uses: ramsey/composer-install@v3

      - name: Run PHP CodeSniffer
        if: always()
        run: vendor/bin/phpcs --report=checkstyle | cs2pr

      - name: Run Psalm
        if: always()
        run: vendor/bin/psalm --output-format=github

      - name: Run PHPStan
        if: always()
        run: vendor/bin/phpstan analyse --error-format=github
